package com.lasho.mybatis.unpage;

import com.lasho.mybatis.unpage.Code;
import com.lasho.mybatis.unpage.CodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    int countByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    int deleteByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    int insert(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    int insertSelective(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    List<Code> selectByExampleWithBLOBs(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    List<Code> selectByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    Code selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    int updateByExampleSelective(@Param("record") Code record, @Param("example") CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") Code record, @Param("example") CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    int updateByExample(@Param("record") Code record, @Param("example") CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    int updateByPrimaryKeySelective(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    int updateByPrimaryKey(Code record);
}