package com.lasho.mybatis.unpage;

public class Code {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.id
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.code
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.sp_id
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    private Integer spId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.pasword
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    private String pasword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.remark
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.id
     *
     * @return the value of code.id
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.id
     *
     * @param id the value for code.id
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.code
     *
     * @return the value of code.code
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.code
     *
     * @param code the value for code.code
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.sp_id
     *
     * @return the value of code.sp_id
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    public Integer getSpId() {
        return spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.sp_id
     *
     * @param spId the value for code.sp_id
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    public void setSpId(Integer spId) {
        this.spId = spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.pasword
     *
     * @return the value of code.pasword
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    public String getPasword() {
        return pasword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.pasword
     *
     * @param pasword the value for code.pasword
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    public void setPasword(String pasword) {
        this.pasword = pasword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.remark
     *
     * @return the value of code.remark
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.remark
     *
     * @param remark the value for code.remark
     *
     * @mbggenerated Fri Feb 14 17:12:07 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}